import { Box} from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Login from "./Login/Login";

const Home: NextPage = () => {
  return (
    <Box>
      <Head>
        <title>Zaktodo.uz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logop.png" />
      </Head>

      <Login/>
    
    </Box>
  );
};

export default Home;
